// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDjVHDAgw0cOy70EkQzv-oXR_aTmIFq08',
    appId: '1:652533672362:web:0c5651dd4fe382de6e23d3',
    messagingSenderId: '652533672362',
    projectId: 'temaqui-1d3cb',
    authDomain: 'temaqui-1d3cb.firebaseapp.com',
    storageBucket: 'temaqui-1d3cb.appspot.com',
    measurementId: 'G-RP8HDF00BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAuP5HuMSADOnlU3fTehBbKKN6sSjYEBQ',
    appId: '1:652533672362:android:f61a2991b821fc516e23d3',
    messagingSenderId: '652533672362',
    projectId: 'temaqui-1d3cb',
    storageBucket: 'temaqui-1d3cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3g7Krbez8Rl-rjKZI6RtyMOm1IWQw3E',
    appId: '1:652533672362:ios:ba572c18180defdd6e23d3',
    messagingSenderId: '652533672362',
    projectId: 'temaqui-1d3cb',
    storageBucket: 'temaqui-1d3cb.appspot.com',
    iosClientId: '652533672362-j617oe908dr69j57dgl62vl7p1hn9gub.apps.googleusercontent.com',
    iosBundleId: 'com.example.temaqui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3g7Krbez8Rl-rjKZI6RtyMOm1IWQw3E',
    appId: '1:652533672362:ios:ba572c18180defdd6e23d3',
    messagingSenderId: '652533672362',
    projectId: 'temaqui-1d3cb',
    storageBucket: 'temaqui-1d3cb.appspot.com',
    iosClientId: '652533672362-j617oe908dr69j57dgl62vl7p1hn9gub.apps.googleusercontent.com',
    iosBundleId: 'com.example.temaqui',
  );
}
